POST http://localhost:6000/register
Content-Type: application/json

{
  "username": "test",
  "password": "test",
  "email": "test@boop.com"
}

###

POST http://localhost:6000/login
Content-Type: application/json

{
  "username": "dennis",
  "password": "gyorgy"
}

###

GET http://localhost:5000/api/v1/pokemon/77
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzczMzE5ODU0ZjVmMDhhMmEzYzM1Y2IiLCJpYXQiOjE2Njg0OTM3Mjh9.KkcggNh_6WtiDN0hEG0Ig5OL4zGIJgud6t7eGv93kwY